- name: payment setup
  hosts: all
  become: yes
  tasks:
    - name: install nodejs
      ansible.builtin.dnf:
        name: python3-pip
        state: present
    - name: creation of appuser using user module
      ansible.builtin.user:
        name: appuser
        shell: /bin/false
        system: yes
        state: present
    - name: remove existing app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: create app directory if not exists
      ansible.builtin.file:
        path: /app
        state: directory
        owner: appuser
        group: appuser
        mode: '0755'
    - name: download app source code
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/payment.zip
        dest: /tmp/payment.zip
    - name: unarchive the source code to app directory
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes
    - name: install python dependencies
      ansible.builtin.shell: |
        pip3 install -r /app/requirements.txt
        chown -R appuser:appuser /app
        chmod o-rwx /app -R
    - name: check if payment service file exists
      ansible.builtin.stat:
        path: /etc/systemd/system/payment.service
      register: payment_service_file
    - name: remove existing payment service file
      ansible.builtin.file: 
        path: /etc/systemd/system/payment.service
        state: absent 
      when: payment_service_file.stat.exists
    - name: copy payment service file
      ansible.builtin.copy: 
        dest: /etc/systemd/system/payment.service
        src: payment.service
    - name: daemon reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: yes  
    - name: start payment service
      ansible.builtin.systemd_service:
        name: payment
        state: restarted
        enabled: yes
        